apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-app.fullname" . }}-config
data:
{{- range $filename, $content := .Values.configFiles }}
  {{ $filename }}: |
{{ $content | indent 4 }}
{{- end }}